# Generated by Django 5.2.4 on 2025-07-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
